# Generated by Django 4.2.9 on 2024-01-03 14:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Home",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("designation", models.CharField(max_length=100)),
                ("short_about", models.TextField(blank=True, max_length=500)),
                ("photo", models.ImageField(upload_to="images/")),
                (
                    "datetime",
                    models.DateTimeField(blank=True, default=datetime.datetime.now),
                ),
            ],
        ),
    ]
